package com.ohhoonim.demo_jpa.generatedStrategy;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Table(name = "product_identity")
@Entity
public class ProductIdentityEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private BigDecimal price;

    private LocalDateTime createdAt;

}

// GenerationType.AUTO 옵션과 동일 

/*
    create table product_identity (
        price numeric(38,2),
        created_at timestamp(6),
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    )
 */
 
