package com.ohhoonim.demo_jpa.relation;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Table(name="category_one2many")
@Entity
public class CategoryManyEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @ManyToOne
    @JoinColumn(name = "product_id")
    private ProductOneEntity product ;  // <- fk 컬럼으로 지정됨
}

/*
create table category_one2many (
        id bigint generated by default as identity,
        product_id bigint,   -- <- product_id fk 컬럼
        name varchar(255),
        primary key (id)
    )

alter table if exists category_one2many 
       add constraint FK4skek6898tqbc5s6by9d5pd3x 
       foreign key (product_id) 
       references product_one2many    
 */