package com.ohhoonim.demo_jpa.relation;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Table(name = "product_many2many")
@Entity
public class MtoMProductEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private BigDecimal price;

    private LocalDateTime createdAt;

    @ManyToMany(mappedBy = "products", cascade = CascadeType.ALL)
    private List<MtoMCategoryEntity> categories = new ArrayList<>(); 

}
/*
create table product_many2many (
    price numeric(38,2),
    created_at timestamp(6),
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
)
 */