package com.ohhoonim.demo_jpa.relation;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Table(name = "product_one2many")
@Entity
public class ProductOneEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private BigDecimal price;

    private LocalDateTime createdAt;

    // 아래부분 추가해도 테이블 생성에는 영향 없음
    @OneToMany(mappedBy = "product") // <- (주의) JoinColumn을 사용하면 안됨 
    private List<CategoryManyEntity> categories;
}


/*
create table product_one2many (
        price numeric(38,2),
        created_at timestamp(6),
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    )
 */